# Generated by Django 3.1.5 on 2021-03-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('aadharNumber', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_districtadmin', models.BooleanField(default=False)),
                ('is_centeradmin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('centerPrimaryKey', models.AutoField(primary_key=True, serialize=False)),
                ('centerId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtPrimaryKey', models.AutoField(primary_key=True, serialize=False)),
                ('districtId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('aadharNumber', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contactNumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='vaccine_app.center')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineLot',
            fields=[
                ('lotId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('produced', 'produced'), ('atDistrict', 'atDistrict'), ('atCenter', 'atCenter'), ('consumed', 'consumed')], default='produced', max_length=10)),
                ('productionTimestamp', models.DateTimeField(auto_now_add=True)),
                ('departureTimestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiverVaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField(auto_now_add=True)),
                ('vaccineDose', models.BooleanField(default=False)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiverVaccination', to='vaccine_app.vaccinelot')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiverVaccination', to='vaccine_app.receiver')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictVaccineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalTimestamp', models.DateTimeField(auto_now_add=True)),
                ('departureTimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districtVaccine', to='vaccine_app.district')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='districtVaccine', to='vaccine_app.vaccinelot')),
            ],
        ),
        migrations.CreateModel(
            name='CenterVaccineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivalTimestamp', models.DateTimeField(auto_now_add=True)),
                ('departureTimestamp', models.DateTimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centerVaccine', to='vaccine_app.center')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centerVaccine', to='vaccine_app.vaccinelot')),
            ],
        ),
        migrations.CreateModel(
            name='CenterRegestration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centerRegestrations', to='vaccine_app.center')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Center', to='vaccine_app.district'),
        ),
        migrations.CreateModel(
            name='AccessControlListDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_list_district', to='vaccine_app.district')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_list_district_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'district')},
            },
        ),
        migrations.CreateModel(
            name='AccessControlListCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_list_center', to='vaccine_app.center')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_list_center_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'center')},
            },
        ),
    ]
