# Generated by Django 3.1.5 on 2021-03-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='person',
        ),
        migrations.AlterField(
            model_name='receiver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='receivervaccination',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverVaccination', to='vaccine_app.vaccinelot'),
        ),
    ]
