# Generated by Django 3.1.5 on 2021-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0003_auto_20210329_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centervaccinedata',
            name='arrivalTimestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
