# Generated by Django 3.1.5 on 2021-03-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0005_auto_20210330_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='centervaccinedata',
            name='countOfDosesConsumed',
            field=models.IntegerField(default=0),
        ),
    ]
