# Generated by Django 3.1.5 on 2021-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0006_centervaccinedata_countofdosesconsumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivervaccination',
            name='appointmentDate',
        ),
        migrations.AddField(
            model_name='receiver',
            name='appointmentDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='receivervaccination',
            name='vaccineDose',
            field=models.BooleanField(default=True),
        ),
    ]
