# Generated by Django 3.1.5 on 2021-03-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0007_auto_20210330_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiver',
            name='email',
        ),
    ]
