# Generated by Django 3.1.5 on 2021-03-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0008_remove_receiver_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerregestration',
            name='date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centerregestration',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centerRegestrations', to='vaccine_app.center'),
        ),
        migrations.AlterUniqueTogether(
            name='centerregestration',
            unique_together={('center', 'date')},
        ),
    ]
