# Generated by Django 3.1.5 on 2021-03-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0009_auto_20210330_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='maxCountPerDate',
            field=models.IntegerField(default=0),
        ),
    ]
