# Generated by Django 3.1.5 on 2021-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0010_center_maxcountperdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centervaccinedata',
            name='countOfDosesConsumed',
        ),
        migrations.AddField(
            model_name='vaccinelot',
            name='countOfDosesConsumed',
            field=models.IntegerField(default=0),
        ),
    ]
