# Generated by Django 3.1.5 on 2021-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0011_auto_20210401_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
