# Generated by Django 3.1.5 on 2021-04-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0012_auto_20210406_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='population',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='district',
            name='population',
            field=models.IntegerField(default=1),
        ),
    ]
