# Generated by Django 3.1.5 on 2021-04-13 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0014_auto_20210407_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='districtId',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
