# Generated by Django 3.1.5 on 2021-04-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0015_auto_20210413_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.EmailField(max_length=254)),
                ('key', models.UUIDField(editable=False, unique=True)),
                ('district_name', models.CharField(max_length=255)),
                ('center_name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('person', 'key')},
            },
        ),
    ]
